branches:
  only:
  - generator
language: python
sudo: false
python:
- 2.7
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
install:
- pip install -r requirements.txt

script:
- "lektor build && lektor deploy ghpages"

notifications:
  email:
    on_success: always
    on_failure: always

